# Generated by Django 5.1.4 on 2025-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_keypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='private_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='public_key',
            field=models.TextField(null=True),
        ),
    ]
