# Generated by Django 5.1.4 on 2025-01-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_encrypted_key_message_nonce_message_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='message',
            name='voice_message',
        ),
    ]
