# Generated by Django 5.1.4 on 2025-01-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_voice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
