# Generated by Django 5.1.4 on 2025-02-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_encrypted_key_message_nonce_message_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_key',
            new_name='encrypted_aes_key',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='nonce',
            new_name='encrypted_audio',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='tag',
            new_name='iv',
        ),
    ]
