# Generated by Django 5.1.4 on 2025-08-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_rename_encrypted_key_message_encrypted_aes_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="iv",
        ),
    ]
