# Generated by Django 5.1.4 on 2025-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_remove_message_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reaction",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
